export default {
	RECEIVED_PRODUCT_LIST: "RECEIVED_PRODUCT_LIST",
	RECEIVED_PRODUCT_DATA: "RECEIVED_PRODUCT_DATA",
	MODEL_CHANGED: "MODEL_CHANGED",
	ADD_TO_CART: "ADD_TO_CART",
	REMOVE_FROM_CART: "REMOVE_FROM_CART",
	UPDATE_CART_VISIBILITY: "UPDATE_CART_VISIBILITY"
}